# Generated by Django 3.2 on 2021-10-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('similMercado', '0003_remove_evento_id_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='activo',
        ),
    ]
