# Generated by Django 3.2 on 2021-10-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similMercado', '0005_alter_evento_fecha_de_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_de_compra',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
