# Generated by Django 3.2 on 2021-10-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similMercado', '0006_alter_evento_fecha_de_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha_de_compra',
        ),
        migrations.AddField(
            model_name='evento',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
