# Generated by Django 3.2 on 2021-10-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similMercado', '0007_auto_20211012_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
